#ifndef XTS_MODEL_SEQUENCER_SEQUENCER_CONFIG_HPP
#define XTS_MODEL_SEQUENCER_SEQUENCER_CONFIG_HPP

#define XTS_SEQUENCER_MAX_LPB 16
#define XTS_SEQUENCER_MAX_ROWS 32
#define XTS_SEQUENCER_MAX_PATTERNS 8
#define XTS_SEQUENCER_TOTAL_ROWS 256

#endif // XTS_MODEL_SEQUENCER_SEQUENCER_CONFIG_HPP