#ifndef XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP
#define XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP

#define XTS_SYNTH_LFO_COUNT 3
#define XTS_SYNTH_ENV_COUNT 3
#define XTS_SYNTH_UNIT_COUNT 3
#define XTS_SYNTH_MAX_VOICES 64
#define XTS_SYNTH_FILTER_COUNT 3
#define XTS_SYNTH_PARAM_COUNT 208

#endif // XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP
