#ifndef XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP
#define XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP

#define XTS_VOICE_LFO_COUNT 2
#define XTS_VOICE_ENV_COUNT 3
#define XTS_VOICE_UNIT_COUNT 3
#define XTS_VOICE_FILTER_COUNT 3
#define XTS_SYNTH_MAX_VOICES 16
#define XTS_SYNTH_PARAM_COUNT 208

#define XTS_SYNTH_AUTOMATION_GLOBAL_PLOT 0
#define XTS_SYNTH_AUTOMATION_GLOBAL_LFO 1
#define XTS_SYNTH_AUTOMATION_VOICE_AMP 2 
#define XTS_SYNTH_AUTOMATION_VOICE_LFO1 3
#define XTS_SYNTH_AUTOMATION_VOICE_LFO2 4
#define XTS_SYNTH_AUTOMATION_VOICE_ENV1 5
#define XTS_SYNTH_AUTOMATION_VOICE_ENV2 6
#define XTS_SYNTH_AUTOMATION_VOICE_ENV3 7
#define XTS_SYNTH_AUTOMATION_VOICE_UNIT1 8
#define XTS_SYNTH_AUTOMATION_VOICE_UNIT2 9
#define XTS_SYNTH_AUTOMATION_VOICE_UNIT3 10
#define XTS_SYNTH_AUTOMATION_VOICE_FILTER1 11
#define XTS_SYNTH_AUTOMATION_VOICE_FILTER2 12 
#define XTS_SYNTH_AUTOMATION_VOICE_FILTER3 13

#endif // XTS_MODEL_SYNTH_SYNTH_CONFIG_HPP
